apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 1 * * *"  # Run daily at 1:00 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:6.0
            command:
            - /bin/bash
            - -c
            - |
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              BACKUP_DIR="/backup"
              
              # Create backup
              mongodump --host=mongodb \
                --username=$(cat /etc/mongodb-credentials/username) \
                --password=$(cat /etc/mongodb-credentials/password) \
                --authenticationDatabase=admin \
                --db=cloud-native-app \
                --out=${BACKUP_DIR}/${TIMESTAMP}
              
              # Compress backup
              tar -zcvf ${BACKUP_DIR}/${TIMESTAMP}.tar.gz ${BACKUP_DIR}/${TIMESTAMP}
              
              # Cleanup uncompressed files
              rm -rf ${BACKUP_DIR}/${TIMESTAMP}
              
              # Keep only the 7 most recent backups
              ls -tp ${BACKUP_DIR}/*.tar.gz | grep -v '/$' | tail -n +8 | xargs -I {} rm -- {}
              
              echo "Backup completed: ${TIMESTAMP}.tar.gz"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
            - name: mongodb-credentials
              mountPath: /etc/mongodb-credentials
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mongodb-backup-pvc
          - name: mongodb-credentials
            secret:
              secretName: mongodb-admin-secret
              items:
              - key: username
                path: username
              - key: password
                path: password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi