apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYjovL2FwcHVzZXI6YXBwcGFzc3dvcmRAb25nb2RiOjI3MDE3L2Nsb3VkLW5hdGl2ZS1hcHA=  # mongodb://appuser:apppassword@mongodb:27017/cloud-native-app
  username: YXBwdXNlcg== # appuser
  password: YXBwcGFzc3dvcmQ= # apppassword