apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYjovL2FwcHVzZXI6YXBwcGFzc3dvcmRAbW9uZ29kYjoyNzAxNy9jbG91ZC1uYXRpdmUtYXBw  # mongodb://appuser:apppassword@mongodb:27017/cloud-native-app
  username: YXBwdXNlcg== # appuser
  password: YXBwcGFzc3dvcmQ= # apppassword