apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-mongo.js: |
    db = db.getSiblingDB('cloud-native-app');
    db.createUser({
      user: 'appuser',
      pwd: 'apppassword',
      roles: [
        {
          role: 'readWrite',
          db: 'cloud-native-app'
        }
      ]
    });